"""remove address column from User table

Revision ID: 0557f52b594f
Revises: c29d7548d73f
Create Date: 2020-06-27 15:07:11.948452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0557f52b594f'
down_revision = 'c29d7548d73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
