"""add office to User table

Revision ID: 6497c97b1986
Revises: 6f7075255003
Create Date: 2020-06-27 17:58:22.283137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6497c97b1986'
down_revision = '6f7075255003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('office', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'office')
    # ### end Alembic commands ###
