"""add flightplans table

Revision ID: bbe6c99a8fdd
Revises: 49d0898c4802
Create Date: 2020-06-29 02:04:03.235958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe6c99a8fdd'
down_revision = '49d0898c4802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isim_flightplans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scenario_id', sa.INTEGER(), nullable=True),
    sa.Column('flight_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('callsign', sa.VARCHAR(length=10), nullable=True),
    sa.Column('routes', sa.TEXT(), nullable=False),
    sa.Column('enroute_only', sa.BOOLEAN(), nullable=True),
    sa.Column('origin', sa.VARCHAR(length=10), nullable=True),
    sa.Column('destination', sa.VARCHAR(length=10), nullable=True),
    sa.Column('departure_time', sa.INTEGER(), nullable=True),
    sa.Column('cruising_level', sa.INTEGER(), nullable=True),
    sa.Column('cruising_speed', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('isim_flightplans')
    # ### end Alembic commands ###
