"""add last_update to flightplans table

Revision ID: f65eb89a0314
Revises: bbe6c99a8fdd
Create Date: 2020-06-29 02:05:00.808442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f65eb89a0314'
down_revision = 'bbe6c99a8fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('isim_flightplans', sa.Column('last_update', sqlite.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('isim_flightplans', 'last_update')
    # ### end Alembic commands ###
